# Generated by Django 5.1.3 on 2024-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Data de Publicação'),
        ),
    ]
