# Generated by Django 5.1.3 on 2024-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='cpf',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='autor',
            name='telefone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='editora',
            name='telefone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
