# Generated by Django 5.1.3 on 2024-11-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='devolucao',
        ),
    ]
