# Generated by Django 5.1.3 on 2024-11-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_emprestimo_livro_livro_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livros',
            field=models.ManyToManyField(to='app.livro'),
        ),
    ]
